# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.1.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-11T19:37:03Z"
  labels:
    app: koreader-sync-pod
  name: koreader-sync-pod
spec:
  selector:
    app: koreader-sync-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-11T19:37:03Z"
  labels:
    app: koreader-sync-pod
  name: koreader-sync-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/b1n4ryj4n/koreader-sync:latest
    name: koreader-sync
    securityContext:
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /app/data
      name: koreader-sync-data-pvc
  volumes:
  - name: koreader-sync-data-pvc
    persistentVolumeClaim:
      claimName: koreader-sync-data
