# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-09T01:10:11Z"
  labels:
    app: eclipse-mosquitto
  name: eclipse-mosquitto
spec:
  ports:
    - name: "1883"
      nodePort: 30422
      port: 1883
      targetPort: 1883
  selector:
    app: eclipse-mosquitto
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/eclipse-mosquitto: registry
  creationTimestamp: "2023-02-09T01:10:11Z"
  labels:
    app: eclipse-mosquitto
  name: eclipse-mosquitto
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - /usr/sbin/mosquitto
        - -c
        - /mosquitto/config/mosquitto.conf
      image: docker.io/library/eclipse-mosquitto:latest
      name: eclipse-mosquitto
      ports:
        - containerPort: 1883
          hostPort: 1883
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /mosquitto/config/
          name: eclipse-mosquitto-config-host
        - mountPath: /mosquitto/data/
          name: eclipse-mosquitto-data-pvc
        - mountPath: /mosquitto/log/
          name: eclipse-mosquitto-log-pvc
  enableServiceLinks: false
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/core/Projects/eclipse-mosquitto-config
        type: Directory
      name: eclipse-mosquitto-config-host
    - name: eclipse-mosquitto-data-pvc
      persistentVolumeClaim:
        claimName: eclipse-mosquitto-data
    - name: eclipse-mosquitto-log-pvc
      persistentVolumeClaim:
        claimName: eclipse-mosquitto-log
