# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-09T01:09:01Z"
  labels:
    app: home-assistant-pod
  name: home-assistant-pod
spec:
  selector:
    app: home-assistant-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/home-assistant: registry
    io.kubernetes.cri-o.TTY/home-assistant: "false"
    io.podman.annotations.autoremove/home-assistant: "TRUE"
    io.podman.annotations.cid-file/home-assistant: /run/user/1000/container-home-assistant.service.ctr-id
    io.podman.annotations.init/home-assistant: "FALSE"
    io.podman.annotations.privileged/home-assistant: "FALSE"
    io.podman.annotations.publish-all/home-assistant: "FALSE"
  creationTimestamp: "2023-02-09T01:09:01Z"
  labels:
    app: home-assistant-pod
  name: home-assistant-pod
spec:
  automountServiceAccountToken: false
  containers:
    - image: ghcr.io/home-assistant/home-assistant:stable
      name: home-assistant
      securityContext:
        capabilities: {}
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /config
          name: home-assistant-config-host-0
  enableServiceLinks: false
  volumes:
    - hostPath:
        path: /home/jordan/container-volumes/home-assistant-config
        type: Directory
      name: home-assistant-config-host-0
