apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
type: Opaque
stringData:
  miniflux_admin_password: ''
  miniflux_database_url: 'postgres://miniflux:RX4iqhQGVGIRqAa4jnMkrwtPmEdjFL@localhost/miniflux?sslmode=disable'
  miniflux_db_password: ''
