= Home Lab Helm
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
:keywords: container helm k8s kubernetes linux podman systemd
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Kubernetes YAML and https://podman.io/[Podman] systemd configuration files for running my home containers.

Everything is meant to be run rootless via Podman.
The configuration is intended for systems using https://selinuxproject.org/page/Main_Page[SELinux].
https://fedoraproject.org/iot/[Fedora IoT] is the current OS used for deployment.

== Usage

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/home-lab-helm.git
----

. Change to the project directory.
+
[,sh]
----
cd home-lab-helm
----

. Create the directory for Podman's systemd container generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Copy in the network file.
+
[,sh]
----
cp podman.network ~/.config/containers/systemd/
----

. Copy in the desired '.kube' files for the desired applications.
+
[,sh]
----
cp caddy.kube ~/.config/containers/systemd/
----

. For any containers that require secrets, enter the secrets in the corresponding `-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1
----
====

. Import the secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube caddy-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the desired units.
+
[,sh]
----
systemctl --user start caddy
----

== Services

https://caddyserver.com/[Caddy] is used on per-machine basis as a reverse-proxy to manage connections between the containers and everything external to the host.
Caddy configuration files for these services are stored in the https://github.com/jwillikers/caddy-config[Caddy Config] repository.
Anything that allows using a choice of database uses https://www.postgresql.org/[PostgreSQL].

== References

.Documentation
* https://docs.podman.io/en/latest/[Podman Documentation]
* https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html[podman-systemd.unit]
* https://www.freedesktop.org/software/systemd/man/latest/[systemd Manual Pages]

== License

This project is licensed under the https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]
