= Home Lab Helm
Jordan Williams <jordan@jwillikers.com>
:keywords: container helm k8s kubernetes linux podman systemd
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:podman-system-unit: https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html[podman-systemd.unit]

Kubernetes YAML and Podman systemd configuration files for running my home containers.
Currently, everything is run rootless via Podman.

== Usage

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/home-lab-helm.git
----

. Change to the project directory.
+
[,sh]
----
cd home-lab-helm
----

. Create the directory for Podman's systemd container generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Copy in the network file.
+
[,sh]
----
cp podman.network ~/.config/containers/systemd/
----

. Copy in the desired '.kube' files for the desired applications.
+
[,sh]
----
cp caddy.kube ~/.config/containers/systemd/
----

. For any containers that require secrets, enter the secrets in the corresponding `-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1
----
====

. Import the secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube caddy-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the desired units.
+
[,sh]
----
systemctl --user start caddy
----

== References

.Documentation
* https://docs.podman.io/en/latest/[Podman Documentation]
* https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html[podman-systemd.unit]
* https://www.freedesktop.org/software/systemd/man/latest/[systemd Manual Pages]

== License

This project is licensed under the https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Commons Attribution-ShareAlike 4.0 International License].

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]
