= Omada Controller
:experimental:
:icons: font
:keywords: ap network omada router tp-link wifi wireless
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Omada: https://www.tp-link.com/us/omada-sdn/[Omada]
:Omada-Software-Controller: https://www.tp-link.com/us/business-networking/omada-sdn-controller/omada-software-controller/[Omada Software Controller]

{Omada} provides software-defined networking for https://www.tp-link.com/us/[TP-Link] products.
The Omada Controller pod provides the {Omada-Software-Controller} using the https://github.com/mbentley/docker-omada-controller[mbentley/omada-controller] image.

== Usage

. Open the necessary ports in the firewall, since rootless Podman won't be able to open these for us.
+
[,sh]
----
sudo firewall-cmd \
  --add-port=8088/tcp \
  --add-port=8043/tcp \
  --add-port=8843/tcp \
  --add-port=27001/udp \
  --add-port=29810/udp \
  --add-port=29811/tcp \
  --add-port=29812/tcp \
  --add-port=29813/tcp \
  --add-port=29814/tcp \
  --permanent
----

. Reload the firewall rules that were just saved.
+
[,sh]
----
sudo firewall-cmd --reload
----

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Configure the process and file limits for the core user in the `/etc/security/limits.d/core.conf` file.
+
--
[NOTE]
====
The limits below are minimums, and can be set higher.
To check the currently configured limits, use `ulimit -u` for the number of processes available to the current user and `ulimit -n` for the number of open file descriptors.
====

./etc/security/limits.d/core.conf
[source]
----
core soft nofile 4096
core hard nofile 8192
core soft nproc 2048
core hard nproc 4096
----
--

. Reboot for the limits to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Create the directory for Podman's systemd generator and the directory for backups.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd ~/container-volumes/omada-controller-backups
----

. Symlink the `podman.network` and `omada-controller.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network omada-controller.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Omada controller.
+
[,sh]
----
systemctl --user start omada-controller
----
