# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.2
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-21T20:14:20Z"
  labels:
    app: miniflux
  name: miniflux
spec:
  selector:
    app: miniflux
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/miniflux-postgres: registry
    io.containers.autoupdate/miniflux-server: registry
  creationTimestamp: "2023-04-21T20:14:20Z"
  labels:
    app: miniflux
  name: miniflux
spec:
  containers:
    - args:
        - postgres
      env:
        - name: POSTGRES_DB
          value: miniflux
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: miniflux
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux-secrets
              key: miniflux_postgres_password
              optional: false
      image: docker.io/library/postgres:bookworm
      name: miniflux-postgres
      resources: {}
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: miniflux-postgres-data
    - env:
        - name: RUN_MIGRATIONS
          value: "1"
        - name: ADMIN_USERNAME
          value: admin
        - name: CREATE_ADMIN
          value: "1"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: miniflux-secrets
              key: miniflux_database_url
              optional: false
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux-secrets
              key: miniflux_admin_password
              optional: false
      image: ghcr.io/miniflux/miniflux:latest
      name: miniflux-server
      resources: {}
      securityContext:
        seLinuxOptions:
          type: spc_t
  hostUsers: false
  hostname: miniflux
  restartPolicy: Never
  volumes:
    - hostPath:
        path: /home/core/container-volumes/miniflux-postgres-data
        type: Directory
      name: miniflux-postgres-data-host
status: {}
