= Miniflux
:experimental:
:icons: font
:keywords: feed miniflux read reader rss
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Miniflux: https://miniflux.app/[Miniflux]

The {Miniflux} pod provides a simple RSS feed reader.

== Usage

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `miniflux.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/miniflux.caddyfile ~/Projects/caddy-config/sites-enabled/
----

. Copy the `miniflux-secrets.yaml.template` file to `miniflux-secrets.yaml`. 
+
[,sh]
----
cp miniflux-secrets.yaml.template miniflux-secrets.yaml
----

. Fill in any missing secrets in the `miniflux-secrets.yaml` file.
+
--
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

[NOTE]
====
Avoid special characters for the PostgreSQL password to avoid having to escape special characters in the PostgreSQL URL.
====
--

. Import the `miniflux-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube miniflux-secrets.yaml
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Symlink the `podman.network` and `miniflux.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network miniflux.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Miniflux pod.
+
[,sh]
----
systemctl --user start miniflux
----
