apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
type: Opaque
stringData:
  vaultwarden_admin_token: ''
  vaultwarden_database_url: 'postgresql://vaultwarden:[password]@localhost:5432/vaultwarden'
  vaultwarden_postgresql_password: ''
  vaultwarden_smtp_password: ''
