# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-08T22:30:09Z"
  labels:
    app: gitea
  name: gitea
spec:
  ports:
    - name: "22"
      nodePort: 30341
      port: 22
      targetPort: 22
  selector:
    app: gitea
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/gitea-postgresql: registry
    io.containers.autoupdate/gitea-server: registry
  creationTimestamp: "2023-02-08T22:30:09Z"
  labels:
    app: gitea
  name: gitea
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - postgres
      env:
        - name: POSTGRES_DB
          value: gitea
        - name: POSTGRES_USER
          value: gitea
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: gitea_postgresql_password
              optional: false
      image: docker.io/library/postgres:latest
      name: postgresql
      ports:
        - containerPort: 2222
          hostPort: 22
      resources: {}
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: gitea-postgresql-data-host
    - env:
        - name: GITEA__database__NAME
          value: gitea
        - name: GITEA__database__HOST
          value: localhost:5432
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: gitea_postgresql_password
              optional: false
        - name: GITEA__database__DB_TYPE
          value: postgres
        - name: GITEA__database__USER
          value: gitea
        - name: GITEA__server__DOMAIN
          value: gitea.jwillikers.io
        - name: GITEA__server__SSH_DOMAIN
          value: gitea.jwillikers.io
        - name: GITEA__server__ROOT_URL
          value: https://gitea.jwillikers.io
        - name: GITEA__storage__MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: gitea_minio_access_key_id
              optional: false
        - name: GITEA__storage__MINIO_BUCKET
          value: gitea
        - name: GITEA__storage__MINIO_ENDPOINT
          value: minio.jwillikers.io
        - name: GITEA__storage__MINIO_LOCATION
          value: us-east-1
        - name: GITEA__storage__MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: gitea_minio_secret_access_key
              optional: false
        - name: GITEA__storage__MINIO_USE_SSL
          value: true
        - name: GITEA__storage__SERVE_DIRECT
          value: true
        - name: GITEA__storage__STORAGE_TYPE
          value: minio
      image: docker.io/gitea/gitea:latest-rootless
      name: gitea-server
      resources: {}
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/gitea
          name: gitea-server-data-host
        - mountPath: /etc/gitea
          name: gitea-server-config-host
  enableServiceLinks: false
  hostUsers: false
  hostname: gitea
  volumes:
    - hostPath:
        path: /home/core/container-volumes/gitea-postgresql-data
        type: Directory
      name: gitea-postgresql-data-host
    - hostPath:
        path: /home/core/container-volumes/gitea-server-data
        type: Directory
      name: gitea-server-data-host
    - hostPath:
        path: /home/core/container-volumes/gitea-server-config
        type: Directory
      name: gitea-server-config-host
status: {}
