= Gitea
:experimental:
:icons: font
:keywords: git gitea vcs version
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Gitea: https://about.gitea.com/[Gitea]

The {Gitea} pod provides a Gitea server which utilizes the S3-compatible object storage from Minio as the storage backend.
Gitea provides an official https://gitea.com/gitea/helm-chart[Gitea Helm Chart].
Some additional documentation is available in the https://docs.gitea.com/installation/install-on-kubernetes[Installation with Helm (on Kubernetes)] page.

== Usage

The Gitea server uses the standard SSH port, port `22`.
The host listens for SSH on port `2222` instead.

. Set up the Minio Server pod, which the Gitea pod uses as its storage backend.
Follow the steps in the <<../minio/README.adoc,Minio README>>.

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Open the necessary ports in the firewall, since rootless Podman won't be able to open these for us.
+
[,sh]
----
sudo firewall-cmd --add-port=2222/tcp --permanent
----

. Reload the firewall rules that were just saved.
+
[,sh]
----
sudo firewall-cmd --reload
----

. Label the port `2222` for SSH.
+
[,sh]
----
sudo semanage port -a -t ssh_port_t -p tcp 2222
----

. Configure the SSH daemon on the host to listen on port `2222`.
+
./etc/ssh/sshd_config.d/port-2222.conf
[source]
----
Port 2222
----

. Load the updated SSH configuration.
+
[,sh]
----
sudo systemctl restart sshd
----

. Optionally, configure SSH clients to use the port `2222` to access the host.footnote:[I'm terrible at remembering.]
+
.~/.ssh/config
[source]
----
Host rockpro64
  Port 2222
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Symlink the `podman.network` and `gitea.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network gitea.kube ~/.config/containers/systemd/
----

. Create a `gitea` bucket in MinIO.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  quay.io/minio/mc:latest \
  mb jwillikers/gitea
----

. Generate an access token for the Minio server which uses the `gitea-minio-policy.json` policy.
+
--
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume ./gitea-minio-policy.json:/gitea-minio-policy.json:Z \
  quay.io/minio/mc:latest \
  admin user svcacct add --description "Gitea storage backend" --name "Gitea" --policy "gitea-minio-policy.json" jwillikers core
Access Key: XXXXXXXXXXXXXXXXXXXX
Secret Key: ****************************************
Expiration: no-expiry
----

Unless provided explicitly, an access key and secret key will be generated by MinIO.
Use these values in the next step.
--

. Fill in any missing secrets in the `gitea-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `gitea-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube gitea-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Gitea pod.
+
[,sh]
----
systemctl --user start gitea
----

== SSH Container Passthrough

[,sh]
----
sudo setsebool -P sshd_launch_containers on
----

[,sh]
----
systemctl --user start podman.socket
----

// ./etc/sudoers.d/10-git-gitea-shell
// [,sudoers]
// ----
// git meerkat.jwillikers.io = (core) NOPASSWD: /usr/bin/podman exec -i --env SSH_ORIGINAL_COMMAND="$SSH_ORIGINAL_COMMAND" gitea-gitea-server sh "$@"
// ----

./usr/local/bin/gitea-shell
[,sh]
----
#!/usr/bin/env sh
/usr/bin/podman --connection unix:///var/run/user/$(id -u core)/podman/podman.sock exec --env SSH_ORIGINAL_COMMAND="$SSH_ORIGINAL_COMMAND" --interactive gitea-gitea-server sh "$@"
----

sudo groupadd --system core-podman

systemctl --user edit podman.socket

[,sh]
----
[Socket]
SocketGroup=core-podman
----

sudo usermod -aG core-podman core

[,sh]
----
sudo chmod +x /usr/local/bin/gitea-shell
----

[,sh]
----
sudo useradd \
  --create-home \
  --comment "Account for accessing the Gitea container via SSH" \
  --shell /usr/local/bin/gitea-shell \
  --groups core-podman \
  --system \
  git
----

./etc/ssh/sshd_config.d/git.conf
[,sh]
----
Match User git
  AuthorizedKeysCommandUser core
  AuthorizedKeysCommand /usr/bin/podman exec -i gitea-gitea-server /usr/local/bin/gitea keys -e git -u %u -t %t -k %k
----

[,sh]
----
sudo systemctl restart sshd
----

sudo rpm-ostree install audit


[,sh]
----
sudo ausearch -m avc -ts recent -i
\----
type=AVC msg=audit(11/22/2023 11:10:33.535:307) : avc:  denied  { execute } for  pid=2734 comm=sshd name=podman dev="sda3" ino=3747621 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_runtime_exec_t:s0 tclass=file permissive=0
----

[,sh]
----
echo "type=AVC msg=audit(11/22/2023 11:10:33.535:307) : avc:  denied  { execute } for  pid=2734 comm=sshd name=podman dev="sda3" ino=3747621 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:container_runtime_exec_t:s0 tclass=file permissive=0" | audit2allow -m sshd-gitea-container-authorized-keys-command > sshd-gitea-container-authorized-keys-command.te
----

# create a module from the .te file

[,sh]
----
checkmodule -M -m -o sshd-gitea-container-authorized-keys-command.mod sshd-gitea-container-authorized-keys-command.te
----

# package it

[,sh]
----
semodule_package -o sshd-gitea-container-authorized-keys-command.pp -m sshd-gitea-container-authorized-keys-command.mod
----

# install it

[,sh]
----
sudo semodule -i sshd-gitea-container-authorized-keys-command.pp
----
