= Gitea
:experimental:
:icons: font
:keywords: git gitea vcs version
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Gitea: https://about.gitea.com/[Gitea]

The {Gitea} pod provides a Gitea server which utilizes the S3-compatible object storage from Minio as the storage backend.
Gitea provides an official https://gitea.com/gitea/helm-chart[Gitea Helm Chart].
Some additional documentation is available in the https://docs.gitea.com/installation/install-on-kubernetes[Installation with Helm (on Kubernetes)] page.

== Usage

The Gitea server uses the standard SSH port, port `22`.
The host listens for SSH on port `2222` instead.

. Set up the Minio Server pod, which the Gitea pod uses as its storage backend.
Follow the steps in the <<../minio/README.adoc,Minio README>>.

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Open the necessary ports in the firewall, since rootless Podman won't be able to open these for us.
+
[,sh]
----
sudo firewall-cmd --add-port=3000/tcp --add-port=2222/tcp --permanent
----

. Reload the firewall rules that were just saved.
+
[,sh]
----
sudo firewall-cmd --reload
----

. Label the port `2222` for SSH.
+
[,sh]
----
sudo semanage port -a -t ssh_port_t -p tcp 2222
----

. Configure the SSH daemon on the host to listen on port `2222`.
+
./etc/ssh/sshd_config.d/port-2222.conf
[source]
----
Port 2222
----

. Load the updated SSH configuration.
+
[,sh]
----
sudo systemctl restart sshd
----

. Optionally, configure SSH clients to use the port `2222` to access the host.footnote:[I'm terrible at remembering.]
+
.~/.ssh/config
[source]
----
Host rockpro64
     Port 2222
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Symlink the `podman.network` and `gitea.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network gitea.kube ~/.config/containers/systemd/
----

. Create a `gitea` bucket in MinIO.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  quay.io/minio/mc:latest \
  mb jwillikers/gitea
----

. Generate an access token for the Minio server which uses the `gitea-minio-policy.json` policy.
+
--
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume ./gitea-minio-policy.json:/gitea-minio-policy.json:Z \
  quay.io/minio/mc:latest \
  admin user svcacct add --description "Gitea storage backend" --name "Gitea" --policy "gitea-minio-policy.json" jwillikers jordan
Access Key: XXXXXXXXXXXXXXXXXXXX
Secret Key: ****************************************
Expiration: no-expiry
----

Unless provided explicitly, an access key and secret key will be generated by MinIO.
Use these values in the next step.
--

. Fill in any missing secrets in the `gitea-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `gitea-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube gitea-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Gitea pod.
+
[,sh]
----
systemctl --user start gitea
----
