= Forgejo
:experimental:
:icons: font
:keywords: git forgejo vcs version
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Forgejo: https://forgejo.org/[Forgejo]

The {Forgejo} pod provides a Forgejo server which utilizes the S3-compatible object storage from Minio as the storage backend.

== Usage

The forgejo server uses the standard SSH port, port `22`.
The host listens for SSH on port `2222` instead.

. Set up the Minio Server pod, which the forgejo pod uses as its storage backend.
Follow the steps in the <<../minio/README.adoc,Minio README>>.

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `forgejo.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/forgejo.caddyfile ~/Projects/caddy-config/sites-enabled/forgejo.caddyfile
----

. Allow rootless containers to publish to ports 80 and 443 by lowering the starting port for the range of unprivileged ports.
+
./etc/sysctl.d/99-lower-unprivileged_port_start.conf
[source]
----
; Allow publishing to lower port numbers without requiring superuser privileges.
net.ipv4.ip_unprivileged_port_start=22
----

. Load the new sysctl configuration.
+
[,sh]
----
sudo sysctl --system
----

. Open the necessary ports in the firewall, since rootless Podman won't be able to open these for us.
+
[,sh]
----
sudo firewall-cmd --add-port=2222/tcp --permanent
----

. Reload the firewall rules that were just saved.
+
[,sh]
----
sudo firewall-cmd --reload
----

. Label the port `2222` for SSH.
+
[,sh]
----
sudo semanage port -a -t ssh_port_t -p tcp 2222
----

. Configure the SSH daemon on the host to listen on port `2222`.
+
./etc/ssh/sshd_config.d/port-2222.conf
[source]
----
Port 2222
----

. Load the updated SSH configuration.
+
[,sh]
----
sudo systemctl restart sshd
----

. Optionally, configure SSH clients to use the port `2222` to access the host.footnote:[I'm terrible at remembering.]
+
.~/.ssh/config
[source]
----
Host meerkat
  Port 2222
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir --parents ~/.config/containers/systemd
----

. Symlink the `podman.network` and `forgejo.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network forgejo.kube ~/.config/containers/systemd/
----

. Create a `forgejo` bucket in MinIO.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  quay.io/minio/mc:latest \
  mb jwillikers/forgejo
----

. Generate an access token for the Minio server which uses the `forgejo-minio-policy.json` policy.
+
--
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume ./forgejo-minio-policy.json:/forgejo-minio-policy.json:Z \
  quay.io/minio/mc:latest \
  admin user svcacct add --description "forgejo storage backend" --name "forgejo" --policy "forgejo-minio-policy.json" jwillikers core
Access Key: XXXXXXXXXXXXXXXXXXXX
Secret Key: ****************************************
Expiration: no-expiry
----

Unless provided explicitly, an access key and secret key will be generated by MinIO.
Use these values in the next step.
--

. Copy the `forgejo-secrets.yaml.template` file to `forgejo-secrets.yaml`. 
+
[,sh]
----
cp --no-clobber forgejo-secrets.yaml.template forgejo-secrets.yaml
----

. Make sure that the secrets file is not world readable.
+
[,sh]
----
chmod 0640 *-secrets.yaml
----

. Fill in the missing secrets in the `forgejo-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `forgejo-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube forgejo-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Forgejo pod.
+
[,sh]
----
systemctl --user start forgejo
----
