# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/uid: 818
    volume.podman.io/gid: 818
  name: caddy-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/uid: 818
    volume.podman.io/gid: 818
  name: caddy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-04T18:12:52Z"
  labels:
    app: caddy-pod
  name: caddy-pod
spec:
  ports:
    - name: "80"
      nodePort: 32383
      port: 80
      targetPort: 80
    - name: "443"
      nodePort: 31797
      port: 443
      targetPort: 443
  selector:
    app: caddy-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/caddy: registry
  creationTimestamp: "2023-02-04T18:12:52Z"
  labels:
    app: caddy-pod
  name: caddy-pod
spec:
  automountServiceAccountToken: false
  containers:
    - image: quay.io/jwillikers/caddy-ovh:latest
      name: caddy
      env:
        - name: OVH_ENDPOINT
          value: ovh-eu
        - name: OVH_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: caddy-secrets
              key: ovh_application_key
              optional: false
        - name: OVH_APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              name: caddy-secrets
              key: ovh_application_secret
              optional: false
        - name: OVH_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: caddy-secrets
              key: ovh_consumer_key
              optional: false
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "80"
          # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
          - name: net.core.rmem_max
            value: "2500000"
          - name: net.core.wmem_max
            value: "2500000"
      volumeMounts:
        - mountPath: /etc/caddy/
          name: caddy-config-host
        - mountPath: /config/
          name: caddy-config-pvc
        - mountPath: /data/
          name: caddy-data-pvc
        - mountPath: /var/www/html/custom_apps
          name: nextcloud-custom-apps-host
        - mountPath: /var/www/html/data
          name: nextcloud-server-data-host
        - mountPath: /var/www/html
          name: nextcloud-app-host
        - mountPath: /var/www/html/config
          name: nextcloud-config-host
  enableServiceLinks: false
  volumes:
    - hostPath:
        path: /home/core/Projects/caddy-config
        type: Directory
      name: caddy-config-host
    - name: caddy-config-pvc
      persistentVolumeClaim:
        claimName: caddy-config
    - name: caddy-data-pvc
      persistentVolumeClaim:
        claimName: caddy-data
    - hostPath:
        path: /home/core/container-volumes/nextcloud-custom-apps
        type: Directory
      name: nextcloud-custom-apps-host
    - hostPath:
        path: /home/core/container-volumes/nextcloud-server-data
        type: Directory
      name: nextcloud-server-data-host
    - hostPath:
        path: /home/core/container-volumes/nextcloud-app
        type: Directory
      name: nextcloud-app-host
    - hostPath:
        path: /home/core/container-volumes/nextcloud-config
        type: Directory
      name: nextcloud-config-host
