# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/core/container-volumes/nextcloud-app:z
    bind-mount-options/nextcloud-nextcloud-imaginary: /home/core/container-volumes/nextcloud-app:z
    bind-mount-options/nextcloud-nextcloud-postgresql: /home/core/container-volumes/nextcloud-app:z
    bind-mount-options/nextcloud-nextcloud-redis: /home/core/container-volumes/nextcloud-app:z
    bind-mount-options/nextcloud-nextcloud-server: /home/core/container-volumes/nextcloud-app:z
    io.containers.autoupdate/nextcloud-cron: registry
    io.containers.autoupdate/nextcloud-postgresql: registry
    io.containers.autoupdate/nextcloud-imaginary: registry
    io.containers.autoupdate/nextcloud-redis: registry
    io.containers.autoupdate/nextcloud-server: registry
  creationTimestamp: "2023-02-04T18:08:13Z"
  labels:
    app: nextcloud
  name: nextcloud
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - redis-server
      image: docker.io/library/redis:alpine
      name: nextcloud-redis
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /data
          name: nextcloud-redis-data-pvc
    - args:
        - postgres
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_postgresql_password
              optional: false
      image: docker.io/library/postgres:bookworm
      name: nextcloud-postgresql
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: nextcloud-postgresql-data-host
    - args:
        - php-fpm
      env:
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: cloud.jwillikers.io
        - name: OBJECTSTORE_S3_REGION
          value: us-east-1
        - name: SMTP_PORT
          value: "465"
        - name: REDIS_HOST
          value: localhost
        - name: SMTP_NAME
          value: nextcloud@jwillikers.com
        - name: MAIL_DOMAIN
          value: jwillikers.com
        - name: POSTGRES_HOST
          value: localhost
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: OBJECTSTORE_S3_HOST
          value: minio.jwillikers.io
        - name: SMTP_AUTHTYPE
          value: PLAIN
        - name: SMTP_SECURE
          value: ssl
        - name: POSTGRES_USER
          value: nextcloud
        - name: OBJECTSTORE_S3_SSL
          value: "true"
        - name: OBJECTSTORE_S3_BUCKET
          value: nextcloud
        - name: OBJECTSTORE_S3_USEPATH_STYLE
          value: "true"
        - name: OVERWRITECLIURL
          value: https://cloud.jwillikers.io
        - name: TRUSTED_PROXIES
          value: 10.89.0.0/16
        - name: SMTP_HOST
          value: ssl0.ovh.net
        - name: MAIL_FROM_ADDRESS
          value: nextcloud
        - name: POSTGRES_DB
          value: nextcloud
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_smtp_password
              optional: false
        - name: OBJECTSTORE_S3_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_s3_secret
              optional: false
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_admin_password
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_postgresql_password
              optional: false
        - name: OBJECTSTORE_S3_KEY
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: nextcloud_s3_key
              optional: false
      image: docker.io/library/nextcloud:fpm
      name: nextcloud-server
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /var/www/html/custom_apps
          name: nextcloud-custom-apps-host
        - mountPath: /var/www/html/data
          name: nextcloud-server-data-pvc
        - mountPath: /docker-entrypoint-hooks.d/pre-installation
          name: nextcloud-config-docker-entrypoint-hooks.d-pre-installation-host
        - mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          name: nextcloud-config-redis-session.ini-host
        - mountPath: /usr/local/etc/php-fpm.d/z-www-overrides.conf
          name: nextcloud-config-z-www-overrides.conf-host
        - mountPath: /var/www/html
          name: nextcloud-app-host
        - mountPath: /var/www/html/config
          name: nextcloud-config-host
    - args:
        - -concurrency
        - "20"
      env:
        - name: PORT
          value: "8088"
      image: docker.io/nextcloud/aio-imaginary:latest
      name: nextcloud-imaginary
      resources: {}
      securityContext:
        capabilities:
          add:
            - SYS_NICE
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/www/html/custom_apps
          name: nextcloud-custom-apps-host
        - mountPath: /var/www/html/data
          name: nextcloud-server-data-pvc
        - mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          name: nextcloud-config-redis-session.ini-host
        - mountPath: /usr/local/etc/php-fpm.d/z-www-overrides.conf
          name: nextcloud-config-z-www-overrides.conf-host
        - mountPath: /var/www/html
          name: nextcloud-app-host
        - mountPath: /var/www/html/config
          name: nextcloud-config-host
  enableServiceLinks: false
  hostUsers: false
  hostname: nextcloud
  restartPolicy: Never
  volumes:
    - hostPath:
        path: /home/core/container-volumes/nextcloud-custom-apps
        type: Directory
      name: nextcloud-custom-apps-host
    - name: nextcloud-server-data-pvc
      persistentVolumeClaim:
        claimName: nextcloud-server-data
    - hostPath:
        path: /home/core/Projects/nextcloud-config/entrypoint-hooks.d/pre-installation
        type: Directory
      name: nextcloud-config-docker-entrypoint-hooks.d-pre-installation-host
    - hostPath:
        path: /home/core/Projects/nextcloud-config/etc/php/conf.d/redis-session.ini
        type: File
      name: nextcloud-config-redis-session.ini-host
    - hostPath:
        path: /home/core/Projects/nextcloud-config/etc/php-fpm.d/z-www-overrides.conf
        type: File
      name: nextcloud-config-z-www-overrides.conf-host
    - hostPath:
        path: /home/core/container-volumes/nextcloud-app
        type: Directory
      name: nextcloud-app-host
    - hostPath:
        path: /home/core/container-volumes/nextcloud-config
        type: Directory
      name: nextcloud-config-host
    - name: nextcloud-redis-data-pvc
      persistentVolumeClaim:
        claimName: nextcloud-redis-data
    - hostPath:
        path: /home/core/container-volumes/nextcloud-postgresql-data
        type: Directory
      name: nextcloud-postgresql-data-host
status: {}
