= Nextcloud
:experimental:
:icons: font
:keywords: cloud container helm k8s kubernetes linux nextcloud podman redis systemd
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Minio: https://min.io/[Minio]
:Nextcloud: https://nextcloud.com/[Nextcloud]

The {Nextcloud} pod uses the Nextcloud PHP-FPM container image.
Redis provides image caching, and imaginary handles image previews. 
Background maintenance jobs are carried out by a separate container which is executed every five minutes by a systemd timer.
A container for running https://github.com/nextcloud/previewgenerator[Preview Generator] to generate file and image previews at specific intervals is provided as well.

== Usage

This Nextcloud server is configured to use S3-compatible object as primary storage.
In particular, it uses the S3-compatible object storage provided by a local https://min.io/[Minio] instance.
So, configure the Minio server before configuring this Nextcloud instance.
The Caddy container is, of course, used as the reverse-proxy for the Nextcloud server.
However, be sure to use the `caddy-nextcloud.yaml` file instead of the `caddy.yaml` file to run the Caddy container.
The Caddy configuration for Nextcloud mounts in directories from the Nextcloud pod in order to server the site directly.

The Nextcloud pod uses configuration files provided by the https://github.com/jwillikers/nextcloud-config[Nextcloud Config] repository.
In addition, a separate systemd service and timer need to be configured to run background jobs for the Nextcloud server.
Follow the commands below to install the Nextcloud Config repository and configure the container for background jobs.

. Set up the Minio Server pod, which the Nextcloud pod uses as its storage backend.
Follow the steps in the <<../minio/README.adoc,Minio README>>.

. Follow the <<../doc/Redis.adoc#System Configuration,Redis System Configuration>> instructions.

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.
+
[NOTE]
====
The `caddy-nextcloud.kube` file should be used instead of the `caddy.kube` file on the host running Nextcloud.
This uses the appropriate configuration to mount the Nextcloud directories in order to proxy the site via _FastCGI_.
====

. Symlink the `nextcloud.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/nextcloud.caddyfile ~/Projects/caddy-config/sites-enabled/
----

. Clone the Nextcloud Config repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/nextcloud-config.git
----

. Create the directories for Podman's systemd generator and user units.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd ~/.config/systemd/user/
----

. Symlink the `caddy-nextcloud.kube`, `podman.network`, `nextcloud.kube`, `nextcloud-cron.container`, and `nextcloud-cron-previewgenerator.container` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network caddy-nextcloud.kube nextcloud.kube nextcloud-cron.container nextcloud-cron-previewgenerator.container ~/.config/containers/systemd/
----

. Symlink the `nextcloud-cron.timer` and `nextcloud-cron-previewgenerator.timer` files to the `~/.config/systemd/user/` directory.
+
[,sh]
----
ln --force --relative --symbolic nextcloud-cron.timer nextcloud-cron-previewgenerator.timer ~/.config/systemd/user/
----

. Create a `nextcloud` bucket in MinIO.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  quay.io/minio/mc:latest \
  mb jwillikers/nextcloud
----

. Generate an access token for the Minio server which uses the `nextcloud-minio-policy.json` policy.
+
--
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume ./nextcloud-minio-policy.json:/nextcloud-minio-policy.json:Z \
  quay.io/minio/mc:latest \
  admin user svcacct add --description "Nextcloud server storage backend" --name "Nextcloud" --policy "nextcloud-minio-policy.json" jwillikers jordan
Access Key: XXXXXXXXXXXXXXXXXXXX
Secret Key: ****************************************
Expiration: no-expiry
----

Unless provided explicitly, an access key and secret key will be generated by MinIO.
Use these values in the next step.
--

. Fill in any missing secrets in the `nextcloud-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube nextcloud-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Caddy Nextcloud and Nextcloud pods.
+
[,sh]
----
systemctl --user start caddy-nextcloud nextcloud
----

. Wait for the installation of the Nextcloud container to complete.

. Enable and start the timer for the background job container.
+
[,sh]
----
systemctl --user enable --now nextcloud-cron.timer nextcloud-cron-previewgenerator.timer
----

== Maintenance

Update Nextcloud and any apps by running `occ upgrade` in the container.

[,sh]
----
podman exec --tty nextcloud-nextcloud-server ./occ upgrade
----

To generate missing indices, use the following command.

[,sh]
----
podman exec --tty nextcloud-nextcloud-server ./occ db:add-missing-indices
----

Use the command `occ maintenance:mode --off` to disable maintenance mode.

[,sh]
----
podman exec --tty nextcloud-nextcloud-server ./occ maintenance:mode --off
----

== References

.Documentation
* https://github.com/h2non/imaginary[imaginary]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/automatic_configuration.html[Nextcloud Admin Manual: Automatic setup]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html[Nextcloud Admin Manual: Background jobs]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin[Nextcloud Admin Manual: Configuration Parameters - Deleted Items (trash bin)]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html[Nextcloud Admin Manual: File sharing and management - Configuring Object Storage as Primary Storage]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html[Nextcloud Admin Manual: Email]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/index.html[Nextcloud Admin Manual: Nextcloud configuration]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html[Nextcloud Admin Manual: Reverse proxy]
* https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews[Nextcloud Admin Manual: Server tuning - Previews]
* https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#tune-php-fpm[Nextcloud Admin Manual: Server tuning - Tune PHP-FPM]
* https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html[Nextcloud Admin Manual: Transactional file locking]
* https://github.com/nextcloud/docker[Nextcloud Docker]
* https://hub.docker.com/_/redis[redis Official Docker Image] 

.See Also
* https://github.com/nextcloud/all-in-one[Nextcloud All-in-One]
