= Home Assistant
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Home-Assistant: https://www.home-assistant.io/[Home Assistant]

This pod provides a {Home Assistant} server.

== Usage

The ESPHome configuration is kept in the https://github.com/jwillikers/esphome-config[ESPHome Config] repository.

. Clone the https://github.com/jwillikers/esphome-config[ESPHome Config] repository.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/esphome-config.git
----

. Populate the secrets for the configuration in the `~/Projects/esphome-config/esphome/secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Open the default ESPHome HTTP port, 6052, in the firewall, since rootless Podman won't be able to open this for us.
+
[,sh]
----
sudo firewall-cmd --add-port=6052/tcp --permanent
----

. Reload the firewall rules that were just saved.
+
[,sh]
----
sudo firewall-cmd --reload
----

. On Fedora IoT, the _dialout_ group does not exist in the `/etc/group`, so it must be added.
+
[,sh]
----
echo (getent group dialout) | sudo tee -a /etc/group
----

. Now add the user to the _dialout_ group to access serial devices without requiring superuser privileges from the rootless Podman instance.
+
[,sh]
----
sudo usermod --append --groups dialout $USER
----

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. When using a reverse proxy, make sure to enable the necessary settings in the `http` section in `configuration.yaml`.
Here I ensure that trusted proxies include any IP's on the internal Podman CNI network on which my reverse proxy is running, along with it's IPv4 and IPv6 addresses on the Tailscale VPN plus it's IP address on the local network.
+
.~/container-volumes/home-assistant-config/configuration.yaml
[source,yaml]
----
http:
    use_x_forwarded_for: true
    trusted_proxies:
        # localhost
        - ::1
        - 127.0.0.1
        # Tailscale
        - fd7a:115c:a1e0:ab12:4843:cd96:6251:db4b
        - 100.81.219.75
        # LAN
        - 10.1.0.47
        # Docker
        - 172.16.0.0/12
        # Podman
        - 10.88.0.0/16
        - 10.89.0.0/16
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Symlink the `podman.network` and `esphome.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network esphome.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start ESPHome.
+
[,sh]
----
systemctl --user start esphome
----
