= LibreNMS
:experimental:
:icons: font
:keywords: management monitoring network nms php snmp
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:LibreNMS: https://www.librenms.org/[LibreNMS]

The {LibreNMS} configuration provides a LibreNMS service for network monitoring.

== Usage

The LibreNMS Kubernetes YAML uses the configuration provided by the https://codeberg.org/jwillikers/librenms-config[LibreNMS Config] repository.
Certain sensitive parameters are kept in specific files which must be managed separately.
The instructions here document the process get the LibreNMS service up and running.

. Follow the <<../doc/Redict.adoc#System Configuration,Redict System Configuration>> instructions.
. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `librenms.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/librenms.caddyfile ~/Projects/caddy-config/sites-enabled/
----

. Create the `~/Projects` directory.
+
[,sh]
----
mkdir --parents ~/Projects
----

. Clone the LibreNMS Config repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://codeberg.org/jwillikers/librenms-config.git
----

. For each template file in the `~/Projects/librenms-config/config` directory, copy it to the same directory without the `.template` extension.
+
Bash::
+
[,sh]
----
for host_template in ~/Projects/librenms-config/config/*.yaml.template; do cp --no-clobber -- "$host_template" ~/Projects/librenms-config/config/$(basename --no-clobber -- "$host_template" ".template"); done
----

fish::
+
[,sh]
----
for host_template in ~/Projects/librenms-config/config/*.yaml.template; cp --no-clobber -- "$host_template" ~/Projects/librenms-config/config/(basename --no-clobber -- "$host_template" ".template"); end
----

Nushell::
+
[,sh]
----
for host_template in (glob ~/Projects/librenms-config/config/*.yaml.template) { cp --no-clobber $host_template $"($host_template | path parse | reject extension | path join)" }
----

. Make sure that the sensitive files are not world readable.
+
[,sh]
----
chmod 0660 ~/Projects/librenms-config/config/*-credentials.yaml
----

. Determine the UID mappings inside the rootless user's namespace.
+
[,sh]
----
podman unshare cat /proc/self/uid_map
         0        818          1
         1     655360      65536
----

. Do the math to determine the UID outside of the container that is used for user inside the container.
In this case, the container defaults to UID 5665 inside the container.
From the output of the previous command, we can see that UID 1 maps to UID 655360.
The following expression yields the UID outside of the container.
+
[,sh]
----
math 655360 + 0 - 1
655359
----

. Make sure that sensitive files are owned by the subuid that will map to the `root` user in the container.
This command will need to be run by a user allowed to use `sudo`.
+
[,sh]
----
sudo chown --recursive 655359 /home/core/Projects/librenms-config/config
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir --parents ~/.config/containers/systemd
----

. Symlink the `podman.network` and `librenms.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network librenms.kube ~/.config/containers/systemd/
----

. Copy the `librenms-secrets.yaml.template` file to `librenms-secrets.yaml`.
+
[,sh]
----
cp --no-clobber librenms-secrets.yaml.template librenms-secrets.yaml
----

. Make sure that the secrets file is not world readable.
+
[,sh]
----
chmod 0640 *-secrets.yaml
----

. Fill in any missing secrets in the `librenms-secrets.yaml` files.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `librenms-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube librenms-secrets.yaml
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the LibreNMS service.
+
[,sh]
----
systemctl --user enable --now librenms
----

. Scan the network and automatically add devices via SNMP.
+
[,sh]
----
podman exec --interactive --tty --user librenms:librenms librenms-librenms ./snmp-scan.py
----

== Add Devices Manually

To add devices manually, use this command.

Create an API access token https://librenms.jwillikers.io/api-access

.add-device.json
[,json]
----
{
    "authlevel": "authPriv",
    "authname": "monitor",
    "authpass": "******",
    "authalgo": "SHA-256",
    "cryptopass": "******",
    "cryptoalgo": "AES",
    "display": "Meerkat",
    "hostname": "meerkat.jwillikers.io",
    "snmpver": "v3",
    "transport": "udp"
}
----

[,sh]
----
curl -X POST -d @add-device.json -H 'X-Auth-Token: YOURAPITOKENHERE' https://librenms.jwillikers.io/api/v0/devices
----

== Maintenance

[,sh]
----
podman exec --interactive --tty --user librenms:librenms librenms-librenms ./validate.php
----
