apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-21T17:53:56Z"
  labels:
    app: immich
  name: immich
spec:
  selector:
    app: immich
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/immich-machine-learning: registry
    io.containers.autoupdate/immich-microservices: registry
    io.containers.autoupdate/immich-server: registry
    io.containers.autoupdate/postgresql: registry
    io.containers.autoupdate/redis: registry
  creationTimestamp: "2023-04-21T17:53:56Z"
  labels:
    app: immich
  name: immich
spec:
  containers:
    - args:
        - postgres
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: immich
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_postgresql_password
              optional: false
      image: docker.io/library/postgres:latest
      name: postgresql
      resources: {}
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: immich-postgresql-data-host
    - args:
        - redis-server
      image: docker.io/library/redis:latest
      name: redis
      resources: {}
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        # The Redis user and group use the id 999.
        runAsGroup: 999
        runAsUser: 999
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /data
          name: immich-redis-data-pvc
    - args:
        - start.sh
        - immich
      env:
        - name: DB_HOSTNAME
          value: localhost
        - name: DB_DATABASE_NAME
          value: immich
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_postgresql_password
              optional: false
        - name: DB_USERNAME
          value: immich
        - name: IMMICH_CONFIG_FILE
          value: /etc/immich/immich.config.json
        - name: REDIS_HOSTNAME
          value: localhost
        - name: TZ
          value: US/Central
      image: ghcr.io/immich-app/immich-server:release
      name: immich-server
      resources: {}
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /etc/immich/immich.config.json
          name: immich-config-host
        - mountPath: /usr/src/app/upload
          name: immich-uploads-host
    - args:
        - start.sh
        - microservices
      env:
        - name: DB_HOSTNAME
          value: localhost
        - name: DB_DATABASE_NAME
          value: immich
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_postgresql_password
              optional: false
        - name: DB_USERNAME
          value: immich
        - name: IMMICH_CONFIG_FILE
          value: /etc/immich/immich.config.json
        - name: REDIS_HOSTNAME
          value: localhost
        - name: TZ
          value: US/Central
      image: ghcr.io/immich-app/immich-server:release
      name: immich-microservices
      resources: {}
      securityContext:
        # privileged is only allowed as a temporary measure for hardware acceleration. 
        # https://github.com/containers/podman/issues/17833#issuecomment-1925309723
        privileged: true
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /dev/dri
          name: dev-dri-host
        - mountPath: /etc/immich/immich.config.json
          name: immich-config-host
        - mountPath: /usr/src/app/upload
          name: immich-uploads-host
    - env:
        - name: DB_HOSTNAME
          value: localhost
        - name: DB_DATABASE_NAME
          value: immich
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: immich_postgresql_password
              optional: false
        - name: DB_USERNAME
          value: immich
        - name: REDIS_HOSTNAME
          value: localhost
        - name: TZ
          value: US/Central
      image: ghcr.io/immich-app/immich-machine-learning:release
      name: immich-machine-learning
      resources: {}
      securityContext:
        # privileged is only allowed as a temporary measure for hardware acceleration. 
        # https://github.com/containers/podman/issues/17833#issuecomment-1925309723
        privileged: true
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /dev/dri
          name: dev-dri-host
        - mountPath: /cache
          name: immich-immich-machine-learning-cache-pvc
  enableServiceLinks: false
  hostname: immich
  hostUsers: false
  volumes:
    - hostPath:
        path: /dev/dri
        type: Directory
      name: dev-dri-host
    - name: immich-immich-machine-learning-cache-pvc
      persistentVolumeClaim:
        claimName: immich-immich-machine-learning-cache
    - hostPath:
        path: /home/core/Projects/immich-config/immich.config.json
        type: File
      name: immich-config-host
    - hostPath:
        path: /home/core/container-volumes/immich-immich-server-data
        type: Directory
      name: immich-uploads-host
    - hostPath:
        path: /home/core/container-volumes/immich-postgresql-data
        type: Directory
      name: immich-postgresql-data-host
    - name: immich-redis-data-pvc
      persistentVolumeClaim:
        claimName: immich-redis-data
status: {}
