= Immich
:experimental:
:icons: font
:keywords: bitwarden password rust vault vaultwarden
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Immich: https://immich.app/[Immich]

The {Immich} pod provides a service for hosting photographs.

== Usage

The Immich pod uses the configuration file provided by the https://github.com/jwillikers/immich-config[Immich Config] repository.

. Follow the <<../doc/Redis.adoc#System Configuration,Redis System Configuration>> instructions.

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `immich.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/immich.caddyfile ~/Projects/caddy-config/sites-enabled/immich.caddyfile
----

. Create the directory for Podman's configuration file.
+
[,sh]
----
mkdir --parents ~/.config/containers/
----

. Configure Podman to mount in the devices under `/dev/dri` to allow access to the machine's graphics card.
This is a workaround to mount in devices when using Podman with Kubernetes YAML.
Support should eventually be added for doing this with Kubernetes plugins as is standard.
Refer to the Podman issue https://github.com/containers/podman/issues/17833[Support device mapping in kube play similar do Kubernetes device plugins #17833].
+
.~/.config/containers/containers.conf
[,toml]
----
[containers]
devices=["/dev/dri/card0:/dev/dri/card0", "/dev/dri/renderD128:/dev/dri/renderD128"]
----

. Permit container to access devices in SELinux.
+
[,sh]
----
sudo setsebool -P container_use_devices=true
----

. On Fedora IoT, the _video_ and _render_ groups do not exist in `/etc/group`, so they must be added there.
+
[,sh]
----
echo $(getent group render) | sudo tee -a /etc/group; and \
echo $(getent group video) | sudo tee -a /etc/group
----

. Add the core user to the _render_ and _video_ groups to access graphics devices without requiring superuser privileges.
+
[,sh]
----
sudo usermod -aG render,video core
----

. Reboot for the group change to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Clone the Immich Config repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/immich-config.git
----

. Create the necessary host-mount directories.
+
[,sh]
----
mkdir --parents ~/container-volumes/{immich-immich-server-uploads,immich-postgresql-data}
----

. Copy the `immich-secrets.yaml.template` file to `immich-secrets.yaml`. 
+
[,sh]
----
cp --no-clobber immich-secrets.yaml.template immich-secrets.yaml
----

. Make sure that the secrets file is not world readable.
+
[,sh]
----
chmod 0640 *-secrets.yaml
----

. Fill in any missing secrets in the `immich-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `immich-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube immich-secrets.yaml
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir --parents ~/.config/containers/systemd
----

. Symlink the `podman.network` and `immich.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network immich.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Immich pod.
+
[,sh]
----
systemctl --user start immich
----
