= Immich
:experimental:
:icons: font
:keywords: image immich openvino photo photograph picture qsv transcode
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Immich: https://immich.app/[Immich]

The {Immich} pod provides a service for hosting photographs.

== Usage

The Immich pod uses the configuration file provided by the https://github.com/jwillikers/immich-config[Immich Config] repository.
My server uses an 11th gen https://ark.intel.com/content/www/us/en/ark/products/208921/intel-core-i7-1165g7-processor-12m-cache-up-to-4-70-ghz-with-ipu.html[Intel Core i7-1165G7 processor].
This processor's GPU supports Intel Quick Sync Video, a.k.a _QSV_, which provides hardware-accelerated transcoding.
This configuration enables hardware-acceleration for transcoding as well as machine learning for this particular chipset.
The machine learning hardware-acceleration uses https://github.com/openvinotoolkit/openvino[OpenVINO].

. Follow the <<../doc/Hardware Acceleration.adoc,Hardware Acceleration>> documentation to enable hardware acceleration.
. Follow the <<../doc/Redict.adoc#System Configuration,Redict System Configuration>> instructions.
. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `immich.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/immich.caddyfile ~/Projects/caddy-config/sites-enabled/immich.caddyfile
----

. Create the directory for Podman's configuration file.
+
[,sh]
----
mkdir --parents ~/.config/containers/
----

. Clone the Immich Config repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/immich-config.git
----

. Create the necessary host-mount directories.
+
[,sh]
----
mkdir --parents ~/container-volumes/{immich-immich-server-profile,immich-immich-server-upload,immich-postgresql-data}
----

. Copy the `immich-secrets.yaml.template` file to `immich-secrets.yaml`. 
+
[,sh]
----
cp --no-clobber immich-secrets.yaml.template immich-secrets.yaml
----

. Make sure that the secrets file is not world readable.
+
[,sh]
----
chmod 0640 *-secrets.yaml
----

. Fill in any missing secrets in the `immich-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `immich-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube immich-secrets.yaml
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir --parents ~/.config/containers/systemd
----

. Symlink the `podman.network` and `immich.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network immich.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Immich pod.
+
[,sh]
----
systemctl --user start immich
----

== References

.Documentation
* https://wiki.archlinux.org/title/intel_graphics#Enable_GuC_/_HuC_firmware_loading[Arch Linux Wiki: Intel Graphics - Enable GuC / HuC firmware loading]
* https://immich.app/docs/features/hardware-transcoding[Immich: Hardware Transcoding]
* https://immich.app/docs/features/ml-hardware-acceleration[Immich: Hardware-Accelerated Machine Learning]
* https://jellyfin.org/docs/general/administration/hardware-acceleration/intel/#configure-and-verify-lp-mode-on-linux[Jellyfin: Configure And Verify LP Mode On Linux]
