# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.0.3

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-27T19:41:20Z"
  labels:
    app: mediamtx
  name: mediamtx
spec:
  ports:
  - name: "1935"
    nodePort: 31530
    port: 1935
    targetPort: 1935
  - name: "8554"
    nodePort: 30189
    port: 8554
    targetPort: 8554
  - name: "8888"
    nodePort: 31602
    port: 8888
    targetPort: 8888
  - name: "8889"
    nodePort: 32714
    port: 8889
    targetPort: 8889
  - name: "8189"
    nodePort: 32227
    port: 8189
    protocol: UDP
    targetPort: 8189
  - name: "8890"
    nodePort: 30242
    port: 8890
    protocol: UDP
    targetPort: 8890
  selector:
    app: mediamtx
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/mediamtx: registry
  creationTimestamp: "2024-05-27T19:41:20Z"
  labels:
    app: mediamtx
  name: mediamtx
spec:
  containers:
  - env:
    - name: MTX_PROTOCOLS
      value: tcp
    - name: MTX_WEBRTCADDITIONALHOSTS
      value: fd7a:115c:a1e0:ab12:4843:cd96:625f:e80c
    image: docker.io/bluenviron/mediamtx:latest-ffmpeg
    name: mediamtx
    ports:
    - containerPort: 1935
    - containerPort: 8554
    - containerPort: 8888
    - containerPort: 8889
    - containerPort: 8189
      protocol: UDP
    - containerPort: 8890
      protocol: UDP
    securityContext:
      runAsGroup: 818
      runAsUser: 818
      seLinuxOptions:
        type: spc_t
    volumeMounts:
      - mountPath: /mediamtx.yml
        name: mediamtx-config-host
        readOnly: true
  hostUsers: false
  enableServiceLinks: false
  volumes:
    - hostPath:
        path: /home/core/Projects/mediamtx-config/mediamtx.yml
        type: File
      name: mediamtx-config-host
