# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-03T22:25:50Z"
  labels:
    app: jellyfin-pod
  name: jellyfin-pod
spec:
  selector:
    app: jellyfin-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/jellyfin: registry
    io.kubernetes.cri-o.TTY/jellyfin: "false"
    io.podman.annotations.autoremove/jellyfin: "TRUE"
    io.podman.annotations.cid-file/jellyfin: /run/user/1000/container-jellyfin.service.ctr-id
    io.podman.annotations.init/jellyfin: "FALSE"
    io.podman.annotations.privileged/jellyfin: "FALSE"
    io.podman.annotations.publish-all/jellyfin: "FALSE"
  creationTimestamp: "2023-02-03T22:25:50Z"
  labels:
    app: jellyfin-pod
  name: jellyfin-pod
spec:
  automountServiceAccountToken: false
  containers:
    - env:
        - name: JELLYFIN_PublishedServerUrl
          value: jellyfin.jwillikers.io
      image: docker.io/jellyfin/jellyfin:latest
      name: jellyfin
      securityContext:
        capabilities:
          drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /media
          name: media-host
          readOnly: true
        - mountPath: /config
          name: jellyfin-config-pvc
        - mountPath: /cache
          name: jellyfin-cache-pvc
  enableServiceLinks: false
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/core/Media
        type: Directory
      name: media-host
    - name: jellyfin-cache-pvc
      persistentVolumeClaim:
        claimName: jellyfin-config
    - name: jellyfin-cache-pvc
      persistentVolumeClaim:
        claimName: jellyfin-config
