= Jellyfin
:experimental:
:icons: font
:keywords: jellyfin media music s3 s3fs-fuse stream
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Jellyfin: https://jellyfin.org/[Jellyfin]

The {Jellyfin} pod provides an open source media server.

== Usage

Media is stored on S3-compatible object storage from the Minio instance.
Jellyfin does not yet support accessing S3-compatible object storage directly.
The storage is instead mounted to the host filesystem via s3fs.
From there it is mounted inside the container.

. Install the `s3fs-fuse` package.
+
[,sh]
----
sudo rpm-ostree install s3fs-fuse
----

. Reboot.
+
[,sh]
----
sudo systemctl reboot
----

. On Fedora IoT, the _video_ and _render_ groups do not exist in `/etc/group`, so they must be added there.
+
[,sh]
----
echo (getent group render) | sudo tee -a /etc/group; and \
echo (getent group video) | sudo tee -a /etc/group
----

. Add the user to the _render_ and _video_ groups to access certain devices without requiring superuser privileges.
+
[,sh]
----
sudo usermod -aG render,video $USER
----

. Set up the Minio pod.
Follow the steps in the <<../minio/README.adoc,Minio README>>.

. Create a media bucket on Minio.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  quay.io/minio/mc:latest \
  mb jwillikers/minio
----

. Upload media to the Minio instance.
+
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume media:/data:Z \
  quay.io/minio/mc:latest \
  cp --recursive /data/ jwillikers/media
----

. Generate a read-only access token for the Minio server which uses the `jellyfin-minio-policy.json` policy.
+
--
[,sh]
----
podman run \
  --interactive \
  --name minio-client \
  --rm \
  --tty \
  --user $(id -u):$(id -g) \
  --userns keep-id \
  --volume minio-client-config:/.mc:Z \
  --volume ./jellyfin-minio-policy.json:/jellyfin-minio-policy.json:Z \
  quay.io/minio/mc:latest \
  admin user svcacct add --description "Jellyfin media server" --name "Jellyfin" --policy "jellyfin-minio-policy.json" jwillikers jordan
Access Key: XXXXXXXXXXXXXXXXXXXX
Secret Key: ****************************************
Expiration: no-expiry
----

Unless provided explicitly, an access key and secret key will be generated by MinIO.
Use these values in the next step.
--

. Place the access token and secret token in the password file separated by a colon.
+
./etc/passwd-s3fs
[source]
----
ACCESS_KEY_ID:SECRET_ACCESS_KEY
----

. Restrict the permissions on the password file.
+
[,sh]
----
sudo chmod 600 /etc/passwd-s3fs
----

. Create a directory where the media bucket will be mounted.
+
[,sh]
----
mkdir ~/media
----

. Add an entry in `/etc/fstab` to load the bucket from the server using the `s3fs-fuse` driver.
+
--
// todo Add x-systemd.requires=tailscale-online@quartz64.target mount option.

./etc/fstab
[source]
----
s3fs#media /var/home/core/media fuse defaults,_netdev,uid=818,gid=818,compat_dir,nodev,noexec,nofail,noatime,noauto,nosuid,user,x-systemd.automount,x-systemd.idle-timeout=5min,allow_other,use_path_request_style,passwd_file=/etc/passwd-s3fs,url=https://minio.jwillikers.io,context="system_u:object_r:container_file_t:s0" 0 0
----

This mounts the S3 bucket from a MinIO server for use by a particular user, user id 818 and group id 818, and relabels the SELinux context of the directory so that it can be used in containers.
This allows one to mount any of the bucket directories or files in a rootless Podman container.
This is handy for applications that don't yet support using S3-compatible object storage directly.
Additionally, a systemd automount is configured to automatically mount the volume on-demand and unmount it when it has been idle for 5 minutes.
--

. Double check that everything in `/etc/fstab` checks out.
+
[,sh]
----
sudo findmnt --verify --verbose
----

. Reload `/etc/fstab`.
+
[,sh]
----
sudo systemctl daemon-reload
----

. Mount the bucket.
+
[,sh]
----
sudo systemd-mount /var/home/core/media
----

. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir -p ~/.config/containers/systemd
----

. Symlink the `podman.network` and `jellyfin.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network jellyfin.kube ~/.config/containers/systemd/
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Start the Jellyfin pod.
+
[,sh]
----
systemctl --user start jellyfin
----
