# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-26T23:53:35Z"
  labels:
    app: bitcoin-core
  name: bitcoin-core
spec:
  selector:
    app: bitcoin-core
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /var/home/core/container-volumes/bitcoin-core-server-data:z
    io.containers.autoupdate/bitcoin-core-server: registry
    io.containers.autoupdate/bitcoin-core-tor: registry
    io.containers.autoupdate/electrs: registry
  creationTimestamp: "2023-10-26T23:53:35Z"
  labels:
    app: bitcoin-core
  name: bitcoin-core
spec:
  containers:
    - image: docker.io/lncm/tor:latest
      name: bitcoin-core-tor
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /etc/tor
          name: bitcoin-core-config-tor-host
          readOnly: true
        - mountPath: /var/lib/tor
          name: bitcoin-core-tor-data-pvc
        - mountPath: /run/tor
          name: bitcoin-core-tor-run-pvc
    - args:
        - -zmqpubrawblock=tcp://0.0.0.0:28332
        - -zmqpubrawtx=tcp://0.0.0.0:28333
      image: docker.io/lncm/bitcoind:v25.1
      name: bitcoin-core-server
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /.bitcoin
          name: bitcoin-core-server-data-pvc
        - mountPath: /.bitcoin/bitcoin.conf
          name: bitcoin-core-config-bitcoin-bitcoin.conf-host
          readOnly: true
        - mountPath: /.bitcoin/bitcoin.conf.d
          name: bitcoin-core-config-bitcoin-bitcoin.conf.d-host
          readOnly: true
        - mountPath: /run/tor
          name: bitcoin-core-tor-run-pvc
          readOnly: true
    - image: docker.io/getumbrel/electrs:v0.10.1
      name: electrs
      securityContext:
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /data/db
          name: electrs-data-pvc
        - mountPath: /etc/electrs/config.toml
          name: bitcoin-core-config-electrs-config.toml-host
          readOnly: true
        - mountPath: /data/.bitcoin
          name: bitcoin-core-server-data-pvc
          readOnly: true
  hostUsers: false
  volumes:
    - name: bitcoin-core-server-data-pvc
      persistentVolumeClaim:
        claimName: bitcoin-core-server-data
    - hostPath:
        path: /var/home/core/Projects/bitcoin-core-config/electrs/config.toml
        type: File
      name: bitcoin-core-config-electrs-config.toml-host
    - hostPath:
        path: /var/home/core/Projects/bitcoin-core-config/bitcoin/bitcoin.conf
        type: File
      name: bitcoin-core-config-bitcoin-bitcoin.conf-host
    - hostPath:
        path: /var/home/core/Projects/bitcoin-core-config/bitcoin/bitcoin.conf.d
        type: Directory
      name: bitcoin-core-config-bitcoin-bitcoin.conf.d-host
    - name: electrs-data-pvc
      persistentVolumeClaim:
        claimName: electrs-data
    - hostPath:
        path: /var/home/core/Projects/bitcoin-core-config/tor
        type: Directory
      name: bitcoin-core-config-tor-host
    - name: bitcoin-core-tor-data-pvc
      persistentVolumeClaim:
        claimName: bitcoin-core-tor-data
    - name: bitcoin-core-tor-run-pvc
      persistentVolumeClaim:
        claimName: bitcoin-core-tor-run
