# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-04T15:25:42Z"
  labels:
    app: minio-pod
  name: minio-pod
spec:
  ports:
    - name: "9000"
      nodePort: 32029
      port: 9000
      targetPort: 9000
    - name: "9090"
      nodePort: 30262
      port: 9090
      targetPort: 9090
  selector:
    app: minio-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /home/core/s3:z
    io.containers.autoupdate/minio: registry
  creationTimestamp: "2023-02-04T15:25:42Z"
  labels:
    app: minio-pod
  name: minio-pod
spec:
  containers:
    - args:
        - server
        - /data
        - --console-address
        - :9090
      env:
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://console.minio.jwillikers.io
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: minio_root_password
              optional: false
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: minio_root_user
              optional: false
        - name: MINIO_SITE_NAME
          value: closet-1
        - name: MINIO_SITE_REGION
          value: us-east-1
      image: quay.io/minio/minio:latest
      name: minio-server
      ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9090
          hostPort: 9090
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        seLinuxOptions:
          type: spc_t
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /data
          name: home-core-s3-host
        - mountPath: /root/.minio/certs/minio.jwillikers.io/public.crt
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.jwillikers.io-minio.jwillikers.io.crt-host
          readOnly: true
        - mountPath: /root/.minio/certs/minio.jwillikers.io/private.key
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.jwillikers.io-minio.jwillikers.io.key-host
          readOnly: true
        - mountPath: /root/.minio/certs/minio.lan.jwillikers.io/public.crt
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.lan.jwillikers.io-minio.lan.jwillikers.io.crt-host
          readOnly: true
        - mountPath: /root/.minio/certs/minio.lan.jwillikers.io/private.key
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.lan.jwillikers.io-minio.lan.jwillikers.io.key-host
          readOnly: true
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/core/s3
        type: Directory
      name: home-core-s3-host
    - hostPath:
        path: /home/core/container-volumes/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/minio.jwillikers.io/minio.jwillikers.io.crt
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.jwillikers.io-minio.jwillikers.io.crt-host
    - hostPath:
        path: /home/core/container-volumes/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/minio.jwillikers.io/minio.jwillikers.io.key
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.jwillikers.io-minio.jwillikers.io.key-host
    - hostPath:
        path: /home/core/container-volumes/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/minio.lan.jwillikers.io/minio.lan.jwillikers.io.crt
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.lan.jwillikers.io-minio.lan.jwillikers.io.crt-host
    - hostPath:
        path: /home/core/container-volumes/caddy-data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/minio.lan.jwillikers.io/minio.lan.jwillikers.io.key
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-minio.lan.jwillikers.io-minio.lan.jwillikers.io.key-host
