# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-13T17:48:30Z"
  labels:
    app: icinga-pod
  name: icinga-pod
spec:
  selector:
    app: icinga-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/icinga: registry
    io.containers.autoupdate/init-icinga-run-directory: registry
    bind-mount-options: /home/core/Projects/icinga-config/etc:Z
  creationTimestamp: "2023-08-13T17:48:30Z"
  labels:
    app: icinga-pod
  name: icinga-pod
spec:
  initContainers:
    - name: init-icinga-run-directory
      image: docker.io/alpine:latest
      command: ["sh", "-c", "chmod 0700 /run/icinga2"]
      securityContext:
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /run/icinga2
          name: icinga-run-pvc
  containers:
  - args:
    - icinga2
    - daemon
    - -x
    - debug
    env:
    - name: ICINGA_MASTER
      value: "1"
    - name: HOSTNAME
      value: icinga.jwillikers.io
    image: docker.io/icinga/icinga2:latest
    name: icinga
    securityContext:
      capabilities:
        add: ["NET_RAW"]
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /data
      name: icinga-data-pvc
    - mountPath: /data/etc/icinga2
      name: icinga-config-host
      readOnly: True
    - mountPath: /run/icinga2
      name: icinga-run-pvc
  hostname: icinga.jwillikers.io
  volumes:
  - name: icinga-data-pvc
    persistentVolumeClaim:
      claimName: icinga-data
  - name: icinga-run-pvc
    persistentVolumeClaim:
      claimName: icinga-run
  - hostPath:
      path: /home/core/Projects/icinga-config/etc/icinga2
      type: Directory
    name: icinga-config-host
