# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-28T17:59:08Z"
  labels:
    app: icingaweb
  name: icingaweb
spec:
  selector:
    app: icingaweb
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /var/home/core/container-volumes/icingaweb-server-run:Z
    io.containers.autoupdate/icingaweb-postgresql: registry
    io.containers.autoupdate/icingaweb-server: registry
  creationTimestamp: "2023-10-28T17:59:08Z"
  labels:
    app: icingaweb
  name: icingaweb
spec:
  containers:
  - args:
    - postgres
    env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_DB
      value: icingaweb
    - name: POSTGRES_USER
      value: icingaweb
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: icingaweb-secrets
          key: icingaweb_postgresql_password
          optional: false
    image: docker.io/library/postgres:bookworm
    name: icingaweb-postgresql
    securityContext:
      runAsGroup: 387
      runAsUser: 387
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: var-home-core-container-volumes-icingaweb-postgresql-data-host-0
  - args:
    - bash
    - -eo
    - pipefail
    - -c
    - . /etc/apache2/envvars; exec apache2 -DFOREGROUND
    env:
    - name: icingaweb.resources.icingaweb_db.dbname
      value: icingaweb
    - name: icingaweb.resources.icingadb.dbname
      value: icingadb
    - name: icingaweb.resources.icingadb.port
      value: "5432"
    - name: icingaweb.groups.icingaweb2.resource
      value: icingaweb_db
    - name: icingaweb.modules.icingadb.redis.redis1.host
      value: icingadb.dns.podman
    - name: icingaweb.resources.icingaweb_db.host
      value: localhost
    - name: icingaweb.resources.icingadb.username
      value: icingadb
    - name: icingaweb.resources.icingadb.db
      value: pgsql
    - name: icingaweb.modules.icingadb.commandtransports.icinga2.host
      value: icinga.dns.podman
    - name: icingaweb.roles.Administrators.permissions
      value: '*'
    - name: icingaweb.resources.icingaweb_db.username
      value: icingaweb
    - name: icingaweb.resources.icingaweb_db.type
      value: db
    - name: icingaweb.modules.icingadb.redis.redis1.port
      value: "6379"
    - name: icingaweb.authentication.icingaweb2.backend
      value: db
    - name: icingaweb.resources.icingadb.type
      value: db
    - name: icingaweb.resources.icingaweb_db.port
      value: "5432"
    - name: icingaweb.authentication.icingaweb2.resource
      value: icingaweb_db
    - name: icingaweb.modules.icingadb.commandtransports.icinga2.transport
      value: api
    - name: icingaweb.groups.icingaweb2.backend
      value: db
    - name: icingaweb.config.global.config_backend
      value: db
    - name: icingaweb.resources.icingaweb_db.db
      value: pgsql
    - name: icingaweb.modules.icingadb.commandtransports.icinga2.username
      value: icingadb-web
    - name: icingaweb.config.logging.log
      value: php
    - name: icingaweb.config.global.config_resource
      value: icingaweb_db
    - name: icingaweb.roles.Administrators.groups
      value: Administrators
    - name: icingaweb.resources.icingadb.host
      value: icingadb.dns.podman
    - name: icingaweb.modules.icingadb.config.icingadb.resource
      value: icingadb
    - name: icingaweb.enabledModules
      value: icingadb
    - name: icingaweb.roles.Administrators.users
      value: icingaadmin
    - name: icingaweb.resources.icingaweb_db.password
      valueFrom:
        secretKeyRef:
          name: icingaweb-secrets
          key: icingaweb_postgresql_password
          optional: false
    - name: icingaweb.passwords.icingaweb2.icingaadmin
      valueFrom:
        secretKeyRef:
          name: icingaweb-secrets
          key: icingaweb_admin_password
          optional: false
    - name: icingaweb.resources.icingadb.password
      valueFrom:
        secretKeyRef:
          name: icingadb-secrets
          key: icingadb_postgresql_password
          optional: false
    - name: icingaweb.modules.icingadb.commandtransports.icinga2.password
      valueFrom:
        secretKeyRef:
          name: icingaweb-secrets
          key: icinga_icingadb-web_api_user_password
          optional: false
    # todo Use the latest tag when Arm builds are available for it.
    image: docker.io/icinga/icingaweb2:main
    name: icingaweb-server
    securityContext:
      runAsGroup: 387
      runAsUser: 387
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - mountPath: /data
      name: var-home-core-container-volumes-icingaweb-server-data-host-0
    - mountPath: /var/run/apache2
      name: var-home-core-container-volumes-icingaweb-server-run-host-1
  hostUsers: false
  hostname: icingaweb.jwillikers.io
  volumes:
  - hostPath:
      path: /var/home/core/container-volumes/icingaweb-postgresql-data
      type: Directory
    name: var-home-core-container-volumes-icingaweb-postgresql-data-host-0
  - hostPath:
      path: /var/home/core/container-volumes/icingaweb-server-data
      type: Directory
    name: var-home-core-container-volumes-icingaweb-server-data-host-0
  - hostPath:
      path: /var/home/core/container-volumes/icingaweb-server-run
      type: Directory
    name: var-home-core-container-volumes-icingaweb-server-run-host-1
