= Icinga
:experimental:
:icons: font
:keywords: icinga icinga2 icingadb icingaweb monitoring nagios php
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Icinga: https://icinga.com/[Icinga]
:Icinga-DB: https://icinga.com/docs/icinga-db/latest/doc/01-About/[Icinga DB]
:Icinga-2: https://icinga.com/docs/icinga-2/latest/doc/01-about/[Icinga 2]
:Icinga-Web-2: https://icinga.com/docs/icinga-web/latest/[Icinga Web 2]

The {Icinga} charts are collection of three separate charts for providing the primary services that comprise the Icinga monitoring suite.
These charts are for {Icinga-2}, {Icinga-DB}, and {Icinga-Web-2}.
Official helm charts are available from the https://github.com/Icinga/helm-charts[Icinga2 Kubernetes Helm Charts] project.

== Usage

The Icinga 2 chart uses the configuration provided by the https://github.com/jwillikers/icinga-config[Icinga Config] repository.
It uses my https://github.com/jwillikers/icinga-snmp-image[Icinga SNMP Image] which adds several SNMP plugins to the official container image.
Certain sensitive parameters are kept in specific files which must be managed separately.
The instructions here document the process get the Icinga 2, Icinga DB, and Icinga Web 2 services up and running.

[TIP]
====
It is recommend to run Icinga 2 and Icinga DB on the same machine to reduce latency. 
====

. Follow the <<../doc/Redict.adoc#System Configuration,Redict System Configuration>> instructions.
. Follow the <<../caddy/README.adoc,instructions for Caddy>>.

. Symlink the `icingaweb.caddyfile` file to the `sites-enabled` directory.
+
[,sh]
----
ln --force --relative --symbolic ~/Projects/caddy-config/sites-available/icingaweb.caddyfile ~/Projects/caddy-config/sites-enabled/
----

. Open the necessary ports in the firewall, since rootless Podman won't be able to open these for us.
+
[,sh]
----
sudo firewall-cmd --add-port=5665/tcp --permanent
----

. Reload the new firewall rules.
+
[,sh]
----
sudo firewall-cmd --reload
----

. Increase the process limits for the core user in the `/etc/security/limits.d/core.conf` file.
+
./etc/security/limits.d/core.conf
[source]
----
core soft nproc 250000
core hard nproc 500000
----

. Reboot for the limits to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Create the `~/Projects` directory.
+
[,sh]
----
mkdir -p ~/Projects
----

. Clone the Icinga Config repository under the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/icinga-config.git
----

. For each template file in the `~/Projects/icinga-config/etc/icinga2/constants.d` directory, copy it to the same directory without the `.template` extension.
+
Bash::
+
[,sh]
----
for host_template in ~/Projects/icinga-config/etc/icinga2/constants.d/*.conf.template; do cp --no-clobber -- "$host_template" ~/Projects/icinga-config/etc/icinga2/constants.d/$(basename --no-clobber -- "$host_template" ".template"); done
----

fish::
+
[,sh]
----
for host_template in ~/Projects/icinga-config/etc/icinga2/constants.d/*.conf.template; cp --no-clobber -- "$host_template" ~/Projects/icinga-config/etc/icinga2/constants.d/(basename --no-clobber -- "$host_template" ".template"); end
----

Nushell::
+
[,sh]
----
for host_template in (glob ~/Projects/icinga-config/etc/icinga2/constants.d/*.conf.template) { cp --no-clobber $host_template $"($host_template | path parse | reject extension | path join)" }
----

. Fill in any missing credentials in the files in the `~/Projects/icinga-config/etc/icinga2/constants.d` directory, such as SNMPv3 authentication and encryption keys.
+
[NOTE]
====
Be sure to escape characters in string constants.
Escape any `$` with an additional `$` character.
Escape other characters, such as the `"` character,  with a backslash, `\`.
Refer to https://icinga.com/docs/icinga-2/2.10/doc/17-language-reference/#string-literals-escape-sequences[String Literals Escape Sequences] in the https://icinga.com/docs/icinga-2/2.10/doc/17-language-reference/[Language Reference] for which characters need to be escaped.
====

.. Generate the `IcingaDbWebApiPassword`.
This password will be used by Icinga Web 2 to connect to the Icinga 2 instance.
Keep this password handy when filling at the `icingaweb-secrets.yaml` file later.
+
[,sh]
----
echo "const IcingaDbWebApiPassword = \"$(openssl rand -base64 30)\"" | tee ~/Projects/icinga-config/etc/icinga2/constants.d/icingadb-web-api-user-password.conf
----

.. Generate the `TicketSalt`.
+
[,sh]
----
echo "const TicketSalt = \"$(openssl rand -base64 30)\"" > ~/Projects/icinga-config/etc/icinga2/constants.d/ticket-salt.conf
----

. Make sure that the sensitive files are not world readable.
+
[,sh]
----
chmod 0660 ~/Projects/icinga-config/etc/icinga2/constants.d/{*-credentials.conf,*-password.conf,ticket-salt.conf}
----

. Determine the UID mappings inside the rootless user's namespace.
+
[,sh]
----
podman unshare cat /proc/self/uid_map
         0        818          1
         1     655360      65536
----

. Do the math to determine the UID outside of the container that is used for user inside the container.
In this case, the container defaults to UID 5665 inside the container.
From the output of the previous command, we can see that UID 1 maps to UID 655360.
The following expression yields the UID outside of the container.
+
[,sh]
----
math 655360 + 5665 - 1
661024
----

. Make sure that sensitive files are owned by the subuid that will map to the `icinga` user in the container.
This command will need to be run by user allowed to use `sudo`.
+
[,sh]
----
sudo chown 661024 /home/core/Projects/icinga-config/etc/icinga2/constants.d/{*-credentials.conf,*-password.conf,ticket-salt.conf}
----

. Create the directory for Podman's systemd generator.
+
[,sh]
----
mkdir --parents ~/.config/containers/systemd
----

. Symlink the `podman.network`, `icinga.kube`, `icingadb.kube`, and `icingaweb.kube` files to the `~/.config/containers/systemd/` directory.
+
[,sh]
----
ln --force --relative --symbolic ../podman.network icinga.kube icingadb.kube icingaweb.kube ~/.config/containers/systemd/
----

. Copy the `icingadb-secrets.yaml.template` file to `icingadb-secrets.yaml`.
+
[,sh]
----
cp --no-clobber icingadb-secrets.yaml.template icingadb-secrets.yaml
----

. Copy the `icingaweb-secrets.yaml.template` file to `icingaweb-secrets.yaml`.
+
[,sh]
----
cp --no-clobber icingaweb-secrets.yaml.template icingaweb-secrets.yaml
----

. Make sure that the secrets files are not world readable.
+
[,sh]
----
chmod 0640 *-secrets.yaml
----

. Fill in any missing secrets in the `icingadb-secrets.yaml` and `icingaweb-secrets.yaml` files.
Use the password for the `IcingaDbWebApiPassword` as the value for the `icinga_icingadb-web_api_user_password` secret in the `icingaweb-secrets.yaml` file.
+
[TIP]
====
You can generate a random password with the following command.

[,sh]
----
tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1 | tr -d '\n'
----
====

. Import the `icingadb-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube icingadb-secrets.yaml
----

. Import the `icingaweb-secrets.yaml` secrets in Podman with the `podman play kube` command.
+
[,sh]
----
podman play kube icingaweb-secrets.yaml
----

. Initialize Icinga.
+
[,sh]
----
podman run \
  --env ICINGA_MASTER=1 \
  --hostname icinga.jwillikers.io \
  --interactive \
  --network systemd-podman \
  --rm \
  --tty \
  --volume icinga-data:/data:Z \
  docker.io/icinga/icinga2:latest \
  icinga2 node wizard
----

. Load the newly added systemd units.
+
[,sh]
----
systemctl --user daemon-reload
----

. Enable and start the Icinga 2, Icinga DB, and Icinga Web 2 pods.
+
[,sh]
----
systemctl --user enable --now icinga icingadb icingaweb
----

== Validate

Use the following Podman command to validate the Icinga configuration.

[,sh]
----
podman run \
  --env ICINGA_MASTER=1 \
  --hostname icinga.jwillikers.io \
  --interactive \
  --rm \
  --tty \
  --volume icinga-data:/data:Z \
  --volume ~/Projects/icinga-config/etc/icinga2:/data/etc/icinga2:ro,Z \
  docker.io/icinga/icinga2:latest \
  icinga2 daemon --validate
----

== IcingaDB PostgreSQL Migrations

Occasionally, the schema for IcingaDB will be changed, requiring manually applying a new database schema.
The following steps demonstrate how to upgrade the database with the new schema.

. Create the `migrations` directory to place all of the SQL migration scripts.
+
[,sh]
----
mkdir migrations
----

. Download the required migrations from the IcingaDB repository https://github.com/Icinga/icingadb/tree/main/schema/pgsql/upgrades[here].
+
[,sh]
----
curl --location --output-dir migrations --remote-name https://raw.githubusercontent.com/Icinga/icingadb/v1.2.0/schema/pgsql/upgrades/1.2.0.sql
----

. Stop the `icingadb` service.
+
[,sh]
----
systemctl --user stop icingadb
----

. Create the `icingadb` pod.
+
[,sh]
----
podman pod create \
  --name icingadb \
  --network podman \
  --replace \
  --userns keep-id
----

. Run the IcingaDB PostgreSQL container, mounting in the `migrations` directory.
+
[,sh]
----
podman run \
  --detach \
  --env PGDATA=/var/lib/postgresql/data/pgdata \
  --env POSTGRES_DB=icingadb \
  --env POSTGRES_USER=icingadb \
  --health-cmd 'pg_isready -U icingadb' \
  --health-interval 10s \
  --health-start-period 30s \
  --hostuser (id -u) \
  --label "io.containers.autoupdate=registry" \
  --name icingadb-postgresql \
  --rm \
  --pod icingadb \
  // --secret
  --user (id -u):(id -g) \
  --volume icingadb-postgresql-data:/var/lib/postgresql/data:Z \
  --volume (pwd)/migrations:/migrations:Z \
  docker.io/library/postgres:latest
----

. Execute the SQL migration script with the `psql` command as follows.
+
[,sh]
----
podman exec \
  --interactive \
  --tty \
  icingadb-postgresql \
  psql \
    --username=icingadb \
    --dbname=icingadb \
    --echo-all \
    --file=/migrations/1.2.0.sql
----

. Stop the IcingaDB PostgreSQL container.
+
[,sh]
----
podman stop icingadb-postgresql
----

. Stop the IcingaDB pod.
+
[,sh]
----
podman pod stop icingadb
----

. Start the IcingaDB service again.
+
[,sh]
----
systemctl --user start icingadb
----

. Clean up the `migrations` directory.
+
[,sh]
----
rm --force --recursive migrations
----
