# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
    - name: "8086"
      nodePort: 30331
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/influxdb: registry
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  automountServiceAccountToken: false
  initContainers:
    - name: chown-volumes
      image: docker.io/alpine:latest
      command: ["sh", "-c", "chown 818:818 /var/lib/influxdb2"]
      securityContext:
        capabilities:
          drop: ["all"]
          add: ["CHOWN"]
        runAsGroup: 0
        runAsUser: 0
        runAsNonRoot: false
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: influxdb-data-pvc
  containers:
    - args:
        - influxd
      env:
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: jwillikers
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: data
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 56w
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: jordan
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_token
              optional: false
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_password
              optional: false
        - name: INFLUXD_TLS_CERT
          value: /home/influxdb/influxdb.jwillikers.io.public.crt
        - name: INFLUXD_TLS_KEY
          value: /home/influxdb/influxdb.jwillikers.io.public.key
      image: quay.io/influxdb/influxdb:latest
      name: influxdb
      ports:
        - containerPort: 8086
          hostPort: 8086
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /etc/influxdb2/config.yml
          name: influxdb-config-host
          readOnly: true
        - mountPath: /etc/influxdb2
          name: influxdb-config-host
        - mountPath: /var/lib/influxdb2
          name: influxdb-data-pvc
        - mountPath: /home/influxdb/influxdb.jwillikers.io.public.crt
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.jwillikers.io-influxdb.jwillikers.io.crt-host
          readOnly: true
        - mountPath: /home/influxdb/influxdb.jwillikers.io.private.key
          name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.jwillikers.io-influxdb.jwillikers.io.key-host
          readOnly: true
  enableServiceLinks: false
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/core/Projects/influxdb-config/etc/influxdb2/config.yml
        type: File
      name: influxdb-config-host
    - hostPath:
        path: /home/core/container-volumes/influxdb-config
        type: Directory
      name: influxdb-config-host
    - name: influxdb-data-pvc
      persistentVolumeClaim:
        claimName: influxdb-data
    - hostPath:
        path: /home/core/.local/share/containers/storage/volumes/caddy-data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/influxdb.jwillikers.io/influxdb.jwillikers.io.crt
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.jwillikers.io-influxdb.jwillikers.io.crt-host
    - hostPath:
        path: /home/core/.local/share/containers/storage/volumes/caddy-data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/influxdb.jwillikers.io/influxdb.jwillikers.io.key
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.jwillikers.io-influxdb.jwillikers.io.key-host
    - hostPath:
        path: /home/core/.local/share/containers/storage/volumes/caddy-data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/influxdb.lan.jwillikers.io/influxdb.lan.jwillikers.io.crt
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.lan.jwillikers.io-influxdb.lan.jwillikers.io.crt-host
    - hostPath:
        path: /home/core/.local/share/containers/storage/volumes/caddy-data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/influxdb.lan.jwillikers.io/influxdb.lan.jwillikers.io.key
        type: File
      name: caddy-data-caddy-certificates-acme-v02.api.letsencrypt.org-directory-influxdb.lan.jwillikers.io-influxdb.lan.jwillikers.io.key-host
