# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb-pod
  name: influxdb-pod
spec:
  ports:
    - name: "8086"
      nodePort: 30331
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/influxdb: registry
    io.kubernetes.cri-o.TTY/influxdb: "true"
    io.podman.annotations.autoremove/influxdb: "TRUE"
    io.podman.annotations.cid-file/influxdb: /run/user/1000/container-influxdb.service.ctr-id
    io.podman.annotations.init/influxdb: "FALSE"
    io.podman.annotations.privileged/influxdb: "FALSE"
    io.podman.annotations.publish-all/influxdb: "FALSE"
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb-pod
  name: influxdb-pod
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - influxd
      env:
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: jwillikers
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: data
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 56w
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: jordan
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_token
              optional: false
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_password
              optional: false
      image: docker.io/library/influxdb:latest
      name: influxdb
      ports:
        - containerPort: 8086
          hostPort: 8086
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /etc/influxdb2/config.yml
          name: influxdb-config-config.yml-host-0
        - mountPath: /var/lib/influxdb2
          name: influxdb-data-host-1
        - mountPath: /etc/influxdb2
          name: f808e8b2bb7f7205a9bbc01ce0672ddd26576e053157b38fdc9e08e02b500288-pvc
  enableServiceLinks: false
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/jordan/container-volumes/influxdb-config/config.yml
        type: File
      name: influxdb-config-config.yml-host-0
    - hostPath:
        path: /home/jordan/container-volumes/influxdb-data
        type: Directory
      name: influxdb-data-host-1
    - name: f808e8b2bb7f7205a9bbc01ce0672ddd26576e053157b38fdc9e08e02b500288-pvc
      persistentVolumeClaim:
        claimName: f808e8b2bb7f7205a9bbc01ce0672ddd26576e053157b38fdc9e08e02b500288
