# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  ports:
    - name: "8086"
      nodePort: 30331
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.containers.autoupdate/influxdb: registry
  creationTimestamp: "2023-02-09T01:03:34Z"
  labels:
    app: influxdb
  name: influxdb
spec:
  automountServiceAccountToken: false
  initContainers:
    - name: chown-volumes
      image: docker.io/alpine:latest
      command: ["sh", "-c", "chown 818:818 /var/lib/influxdb2"]
      securityContext:
        capabilities:
          drop: ["all"]
          add: ["CHOWN"]
        runAsGroup: 0
        runAsUser: 0
        runAsNonRoot: false
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: influxdb-data-pvc
  containers:
    - args:
        - influxd
      env:
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: jwillikers
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: data
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 56w
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: jordan
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_token
              optional: false
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: influxdb_admin_password
              optional: false
      image: docker.io/library/influxdb:latest
      name: influxdb
      ports:
        - containerPort: 8086
          hostPort: 8086
      securityContext:
        capabilities: {}
        runAsGroup: 818
        runAsUser: 818
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /etc/influxdb2
          name: influxdb-config-host
          readOnly: true
        - mountPath: /var/lib/influxdb2
          name: influxdb-data-pvc
  enableServiceLinks: false
  hostUsers: false
  volumes:
    - hostPath:
        path: /home/core/Projects/influxdb-config/etc/influxdb2
        type: Directory
      name: influxdb-config-host
    - name: influxdb-data-pvc
      persistentVolumeClaim:
        claimName: influxdb-data
